# Kairos Landing Page Deployment Pipeline
# Triggered by: push to main branch in kairos-landing repo

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: E2_MEDIUM

substitutions:
  _SERVICE_NAME: kairos-landing
  _REGION: us-central1
  _PORT: '4321'
  _CONTROL_PLANE_URL: 'https://kairos-control-plane-684614817316.us-central1.run.app'

steps:
  # Install dependencies
  - name: 'node:20'
    id: 'install'
    entrypoint: 'npm'
    args: ['ci']

  # Build Astro application with environment variables
  - name: 'node:20'
    id: 'build'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        export PUBLIC_GOOGLE_CLIENT_ID="$$GOOGLE_CLIENT_ID"
        export PUBLIC_CONTROL_PLANE_API_URL="${_CONTROL_PLANE_URL}"
        export PUBLIC_API_URL="${_CONTROL_PLANE_URL}"
        npm run build
    secretEnv: ['GOOGLE_CLIENT_ID']
    waitFor: ['install']

  # Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    id: 'docker-build'
    args:
      - 'build'
      - '-t'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/kairos/landing:$SHORT_SHA'
      - '-t'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/kairos/landing:latest'
      - '.'
    waitFor: ['build']

  # Push Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    id: 'docker-push'
    args:
      - 'push'
      - '--all-tags'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/kairos/landing'
    waitFor: ['docker-build']

  # Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'deploy'
    args:
      - 'run'
      - 'deploy'
      - '${_SERVICE_NAME}'
      - '--image'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/kairos/landing:$SHORT_SHA'
      - '--region'
      - '${_REGION}'
      - '--port'
      - '${_PORT}'
      - '--allow-unauthenticated'
      - '--platform'
      - 'managed'
    waitFor: ['docker-push']

images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/kairos/landing:$SHORT_SHA'
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/kairos/landing:latest'

timeout: '900s'
tags: ['landing', 'deploy']

availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/google-oauth-client-id/versions/latest
      env: 'GOOGLE_CLIENT_ID'
