# Kairos Landing Page Deployment Pipeline
# Triggers:
#   - Push to main → Deploy to kairos-landing-dev (Dev)
#   - Tag v* → Deploy to kairos-landing (Prod)
#
# Substitutions are set by the trigger:
#   _SERVICE_NAME: kairos-landing-dev (dev) or kairos-landing (prod)
#   _CONTROL_PLANE_URL: api-dev.1kairos.com (dev) or api.1kairos.com (prod)
#   _APP_URL: app-dev.1kairos.com (dev) or app.1kairos.com (prod)

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: E2_MEDIUM

substitutions:
  _SERVICE_NAME: kairos-landing
  _REGION: us-central1
  _PORT: '4321'
  _CONTROL_PLANE_URL: https://api.1kairos.com
  _APP_URL: https://app.1kairos.com

steps:
  # Install dependencies
  - name: 'node:20'
    id: 'install'
    entrypoint: 'npm'
    args: ['ci']

  # Build Astro application with environment variables
  - name: 'node:20'
    id: 'build'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        export PUBLIC_GOOGLE_CLIENT_ID="684614817316-7jguqf1cngtr9dn79kjpnjdmrukdua59.apps.googleusercontent.com"
        export PUBLIC_CONTROL_PLANE_API_URL="${_CONTROL_PLANE_URL}"
        export PUBLIC_API_URL="${_CONTROL_PLANE_URL}"
        export PUBLIC_APP_URL="${_APP_URL}"
        npm run build
    waitFor: ['install']

  # Build Docker image from workspace (includes built dist/)
  - name: 'gcr.io/cloud-builders/docker'
    id: 'docker-build'
    args:
      - 'build'
      - '-t'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/kairos/landing:$SHORT_SHA'
      - '-t'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/kairos/landing:latest'
      - '.'
    waitFor: ['build']

  # Push Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    id: 'docker-push'
    args:
      - 'push'
      - '--all-tags'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/kairos/landing'
    waitFor: ['docker-build']

  # Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'deploy'
    args:
      - 'run'
      - 'deploy'
      - '${_SERVICE_NAME}'
      - '--image'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/kairos/landing:$SHORT_SHA'
      - '--region'
      - '${_REGION}'
      - '--port'
      - '${_PORT}'
      - '--allow-unauthenticated'
      - '--platform'
      - 'managed'
    waitFor: ['docker-push']

images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/kairos/landing:$SHORT_SHA'
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/kairos/landing:latest'

timeout: '900s'
tags: ['landing', 'deploy']
